### ISSUE TITLE
Issue at "import augmentation import *"

### ISSUE THREAD

**Issue by nauman9** [arehmanAzam/3D-CNN_DataGenerator#1] opened 2019-03-28 12:30 UTC
Thankyou for your work.
I have been a issue in running this data generator at from augmentation import *. its says no module name augmentation.
I am using **Notebook.**

**Comment by arehmanAzam** [comment] 2019-03-29 05:32
@nauman9 
we have used augmentation file for doing augmentation on the dataset.
you can use it as i have uploaded it now. or you can comment the augmentation techniques used in the function
` def __data_generation(self, list_IDs_temp):`
line 93 to 128
and also remove random number generation of line 84 and 85.

Thanks.

**Comment by nauman9** [comment] 2019-03-29 09:48
@arehmanAzam 
Can you please provide the function **findLabels**
which is called at **labels_training=findLabels(partition['train'], labels_train)**

Thank-you.

**Comment by arehmanAzam** [comment] 2019-03-29 10:08
@nauman9 
i have uploaded the find_labels.py file. 
import the function from there.

Thanks,

**Comment by nauman9** [comment] 2019-03-29 10:09
Got it!
Thank-you.

**Comment by arehmanAzam** [comment] 2019-03-29 10:10
I guess the issue is resolved.
closing it.
@nauman9  please mark it resolved

**Closed as completed** 2019-03-29 12:56 UTC
